### ISSUE TITLE
Services from /usr/lib/systemd/user/ not listed in drop down menu.

### ISSUE THREAD

**Issue by eviansfulda** [petres/gnome-shell-extension-services-systemd#1]
I'm using costume user level services in my Arch Linux GNOME shell desktop, for example, for [SoundWireServer](https://aur.archlinux.org/packages/soundwire/) and [Lantern](https://aur.archlinux.org/packages/lantern-headless-git/). As I understand, that's not relay an issue, but not implemented. Would be nice be able to add those services too. Otherwise, extension like this was something that was missing from GNOME shell and was bothering me for a while now. Thank you for reading minds! Keep up the good work!

**Comment by petres** [comment]
I added the folder `/usr/lib/systemd/user/`. Maybe it would be better to have it configureable, but could there be still some other places where systemd services are stored?

**Comment by eviansfulda** [comment]
Arch wiki provides much more info than i can think of about [user mode](https://wiki.archlinux.org/index.php/Systemd/User#How_it_works), and how it works, also user mode services don't need privilege escalation, so password prompt is not needed in extension for them, it s like: systemctl --user start foo.service.

**Comment by petres** [comment]
Would it help if there exist an option where you could choose if you want to start it with or without sudo rights? Or should it be like that if the service is defined in that directory?

**Comment by eviansfulda** [comment]
I think it should be defined by directory, also i have a question. Why is authentication changed from pkexec to gksu and how is that better? I didn't have gksu installed, by lucky guess i figure it out, my issue is simply, pyexec prompt looks much better in GNOME shell then gksu prompt and for me this was only reason to install gksu.

**Comment by petres** [comment]
You are right: `pkexec` is nicer, not only graphically, I will change it back! The only reason was, that at my computer `sudo`  is configured not asking for a password at all. I should perhaps simple configure `pkexec` not asking for a password.

**Comment by eviansfulda** [comment]
That would be perfect. Thank You!
