### ISSUE TITLE
System Menu icon larger than others

### ISSUE THREAD

**Issue by beanaroo** [petres/gnome-shell-extension-services-systemd#10]
This is the same for all icon themes.

I have tried forcing icon_size with no luck.

![screenshot from 2016-10-10 00-56-30](https://cloud.githubusercontent.com/assets/1748909/19220264/e9b22466-8e85-11e6-9fd6-e0952c072922.png)

Very useful extension, btw. Thank you very much!

**Comment by petres** [comment]
thanks for reporting, 
which gnome version are you using?

**Comment by petres** [comment]
i had running it on gome 3.20 and 3.22 with different themes, there it works.

**Comment by gnumanx** [comment]
Here on Gnome 3.22 it is too large

**Comment by petres** [comment]
which theme?

**Comment by gnumanx** [comment]
The default on Archlinux, I think Adwaita

**Comment by almereyda** [comment]
Here on Fedora 24 with Vertex theme plus icons it is also too large. Had seen this before.

**Comment by ogarcia** [comment]
Gnome 3.24 on Archlinux without shell theme and same error

**Comment by muflone** [comment]
I've fixed by simply removing or disable the line 46 in extension.js

https://github.com/petres/gnome-shell-extension-services-systemd/blob/f578f68cc327004a460f7f5eaafc97ea84fed45b/services-systemd%40abteil.org/extension.js#L46

```
        } else {
            this.container = new PopupMenu.PopupSubMenuMenuItem("Systemd Services", true);
            // this.container.icon.style_class = 'system-extensions-submenu-icon';
            this.container.icon.icon_name = 'system-run-symbolic';

            Main.panel.statusArea.aggregateMenu.menu.addMenuItem(this.container, 8);
        }
```

**Comment by petres** [comment]
thanks, is comitted

**Comment by goodwillcoding** [comment]
@petres 
Hi great extension, works flawlessly. I am using the menu though and the icon is huge. Any chance you can uploaded updated version to extensions.gnome.org? :-)

I am happy to help in anyway I can.

**Comment by goodwillcoding** [comment]
@petres ... we can fork the extension and republish but it seems silly for 1 line fix. Please republish?

**Comment by petres** [comment]
sorry, done, if anybody want to continue maintain this extionsion, welcome!
