### ISSUE TITLE
Service does not exist.

### ISSUE THREAD

**Issue by mortezabahmani** [petres/gnome-shell-extension-services-systemd#11]
Hi
At the first, I want to say that I'm Persian, so sorry for my bad English, and I'm a newbie in Linux too so I am ashamed if I ask elementary questions.
Thank you for your extension, that's so good but when I wanted to add a service in "services systemd" window, I was confronted with this error message: "Service does not exist." for example I added "kerio-kvc.service", that service is installed and running on my computer, I checked with systemctl status command. So what's the problem?

M.

P.S. I learn a little about user services right now, so i got my answer. but it would be better if you add a section for user services in your extension. thank you. :+1:

**Comment by petres** [comment]
Sorry for the delay! I didn't notice the bug report, but the closing of it. Does it work right now, or do you still have the same problem?
