### ISSUE TITLE
Allow starting instances of disabled template unit files

### ISSUE THREAD

**Issue by Fabi2607** [petres/gnome-shell-extension-services-systemd#12]
A nice feature to add would be to allow the following situation.

I have a template unit file mount@.service in my user directory.
This template handles various remote mount points, configurable by environment files.

All instances are disabled by default. Those instances are only started, if I need them.
I can now add instances which are already active or at least enabled.

But I would like to be able to add entries for instances which do not already exist, e.g. mount@server.

This is prevented by a check, if the unit file exists.
Would it be possible to disable this check for template instances?

It is already possible to add existing instances, but as soon as these are stopped, they are removed from the menu, since the file does no longer exist.

The removal can be reproduced by:
1. starting an instance
2. adding it to the menu
3. closing the gnome tweak tool
4. stopping the service
5. opening tweak tool & plugin settings

**Comment by petres** [comment]
I will it update soon to the gnome extension site
