### ISSUE TITLE
Can't change status (needs root?)

### ISSUE THREAD

**Issue by Utini2000** [petres/gnome-shell-extension-services-systemd#2]
Hey there,

I am on Arch and installed this via extensions.gnome.org. I can add services but not change their status. The button just jumps back to the original state. 

I believe this is because it would need root access ? Maybe it could request the "needs root authentication" pop up ?

Thanks !

**Comment by petres** [comment]
it does usually show the popup! but it uses `gksu`, and maybe you do not have the package `gksu` installed.
but today (the last commit) I changed it to use `pkexec` which is in the package `polkit` and usually installed on every arch systen. this version is still not on extension.gnome.org but already in the arch aur package:
gnome-shell-extension-services-systemd-git

if you want to have it working right now, install `gksu` or the aur package, 
best, peter
