### ISSUE TITLE
Not working on Gnome 3.24

### ISSUE THREAD

**Issue by igorpetrov** [petres/gnome-shell-extension-services-systemd#20]
Icon is missing after upgrade to Gnome 3.24.1.

**Comment by riguco** [comment]
TypeError: redeclaration of let appColumn

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49

**Comment by petres** [comment]
fixed in 9f3f7317c89e63baf6b7fadeb86f7149a527b81a

will upload it on extensions.gnome.org

**Comment by scan09** [comment]
Still not working gnome 3.24

**Comment by scan09** [comment]
Error: Schema org.gnome.shell.extensions.services-systemd could not be found for extension services-systemd@abteil.org. Please check your installation.

Stack trace:
  getSettings@/home/scan/.local/share/gnome-shell/extensions/services-systemd@abteil.org/convenience.js:87:1
  ServicesSystemdSettings<._init@/home/scan/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:18:26
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  buildPrefsWidget@/home/scan/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:488:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:22
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49

**Comment by Gronkdalonka** [comment]
Error: Schema org.gnome.shell.extensions.services-systemd could not be found for extension services-systemd@abteil.org. Please check your installation.

Stack trace:
  getSettings@/home/ddormann/.local/share/gnome-shell/extensions/services-systemd@abteil.org/convenience.js:88
  ServicesSystemdSettings<._init@/home/ddormann/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:18
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/ddormann/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:488
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1

Same on gnome 3.22.3

**Comment by petres** [comment]
sorry, my bad, a packaging fault (the zip file did not contain the schema subfolder). I submited a new version on extensions.gnome.org. Should be soon online there.

**Comment by KGCybeX** [comment]
Hi

Confirmed same issue as @Gronkdalonka and @scan09 

**System Specs:**

- Arch x64 - 4.10.11-1-ARCH
- Gnome - GNOME Shell 3.24.1

**Tried the following:**

Install via AUR:

- Installed fine, extension folder was not found under `.local/share/gnome-shell/extensions`
- Tweak tool did not detect the extension

uninstall and,

**Git manual install**

- Pulled from git
- add policy as required
- copied extension to `.local/share/gnome-shell/extensions`
- enable via `gnome-shell-extension-tool -r services-systemd@abteil.org`

Followed by a stacktrace:

```
Error: Schema org.gnome.shell.extensions.services-systemd could not be found for extension services-systemd@abteil.org. Please check your installation.

Stack trace:
  getSettings@/home/cybex/.local/share/gnome-shell/extensions/services-systemd@abteil.org/convenience.js:87:1
  ServicesSystemdSettings<._init@/home/cybex/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:18:26
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  buildPrefsWidget@/home/cybex/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:488:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:22
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

**Comment by scan09** [comment]
Installed by git works perfect

**Comment by petres** [comment]
@KGCybeX the aur package should also work. Note that it is installed under ``/usr/share/gnome-shell/extensions/``. Also you have to log out and log in that the system recognize the change. Will try to make the logout/login step not necessary (will change the PKBUILD)

**Comment by riguco** [comment]
I installed trough Git and all wordked for me.

**Comment by petres** [comment]
Fixed, already online on extensions.gnome.org.

**Comment by riguco** [comment]
thx!
