### ISSUE TITLE
ERROR on Ubuntu 18.0.4 and GNOME 3.28.2

### ISSUE THREAD

**Issue by klaushauschild1984** [petres/gnome-shell-extension-services-systemd#27]
I could not install this extension -> ERROR.
When I try to open the configuration panel I get this stacktrace:

`Error: Schema org.gnome.shell.extensions.services-systemd could not be found for extension services-systemd@abteil.org. Please check your installation.

Stack trace:
  getSettings@/home/khauschild/.local/share/gnome-shell/extensions/services-systemd@abteil.org/convenience.js:87:15
  ServicesSystemdSettings<._init@/home/khauschild/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:18:26
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/khauschild/.local/share/gnome-shell/extensions/services-systemd@abteil.org/prefs.js:488:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  `

**Comment by petres** [comment]
sorry my fault, will update it today!

**Comment by petres** [comment]
fixed, bundled correctly and uploaded on extensions.gnome.org. has been already reviewed and is online!
