### ISSUE TITLE
Does not work on 3.38

### ISSUE THREAD

**Issue by dev8loper** [petres/gnome-shell-extension-services-systemd#39]
Hi,

plugin not compatible with version 3.38

Based on this: https://github.com/UshakovVasilii/gnome-shell-extension-freon/pull/183

**Fix:** popupServiceItem.js line 25 

Wrong line: 
`this.add(this.restartButton, { expand: false, x_align: St.Align.END });`

Fixed line:
`this.add_child(this.restartButton, { expand: false, x_align: Clutter.ActorAlign.CENTER });`

**Comment by camilo0365** [comment]
@dev8loper Sounds like the time for a PR :smile:

**Comment by pokulo** [comment]
latest commit 7fb03450d22b4fa1386011a1886e46b271344c21 works for me under 3.38, but it was not officially upgraded yet.

If you are using Arch Lunix you could use this AUR package to upgrade https://aur.archlinux.org/packages/gnome-shell-extension-services-systemd-git/ which worked for me.

**Comment by dev8loper** [comment]
Thank you for now I fixed it myself. I will wait for updates for better experience
