### ISSUE TITLE
Installed from extensions.gnome.org, does not get what it's master

### ISSUE THREAD

**Issue by damienalexandre** [petres/gnome-shell-extension-services-systemd#4]
- Ubuntu GNOME 15.10
- Gnome Shell 3.16.4

I installed this extension from gnome.org, but it tries to run gksudo (which is not shipped in ubuntu for a since a long time).

Here is the code in my `.local/share/gnome-shell/extensions/services-systemd@abteil.org/extension.js`:

```
//GLib.spawn_command_line_async('sh -c "pkexec --user root systemctl ' + (active ? 'stop' : 'start') + ' ' + service['service'] + '; exit;"');
GLib.spawn_command_line_async('sh -c "gksudo systemctl ' + (active ? 'stop' : 'start') + ' ' + service['service'] + '; exit;"');
```

It's not what's in this repository master. I would like to use `pkexec`, as it's available right away.

Should I install directly from git? Or is it a release/packaging issue from extensions.gnome.org?

Anyway thanks for this extension, it's badly needed :)

**Comment by petres** [comment]
I changed it today also for the gnome shell version 3.16.* to `pkexec' and uploaded it to official gnome shell extension page. It has to get reviewed before the new version of the extension can be updated. This usually durates a few days. Therefore I would suggest, wait a bit!

**Comment by damienalexandre** [comment]
Thanks a lot!

**Comment by damienalexandre** [comment]
Just to let you know, I got the update this morning and it works perfectly! :sparkles:

**Comment by petres** [comment]
great! thanks!
