### ISSUE TITLE
Feature request: Add support for user services

### ISSUE THREAD

**Issue by freijon** [petres/gnome-shell-extension-services-systemd#5]
Some services don't need root access and are stared with 'systemctl --user start $service', like e.g. Pulseaudio. Unfortunately there is no option to add this kind of service ATM.

**Comment by petres** [comment]
Ok, will implement it, what would be the best way? Adding a checkbox to the add formular?

**Comment by freijon** [comment]
Great! :) Yes, I think that would be the best solution

**Comment by freijon** [comment]
Maybe instead of a checkbox you could check if the .service file lies at /usr/lib/systemd/user and then automatically run it with the --user argument?

**Comment by petres** [comment]
Yeah, that would be also a possibility, which folders can contain user
services? The arch docu (https://wiki.archlinux.org/index.php/Systemd/User)
lists: ~/.config/systemd/user/,  /etc/systemd/user/,
~/.local/share/systemd/user/
and /usr/lib/systemd/user.
But maybe there exist other location in other distros.

**Comment by freijon** [comment]
I'm on Arch as well, don't know if the paths differ for other distributions. I could check on my Xubuntu virtual machine in the evening. I would start with the paths you listed.

**Comment by freijon** [comment]
It's the same for Xubuntu

**Comment by petres** [comment]
Done, I tried to do it without folders, please test it! The arch package has already been updated!

**Comment by freijon** [comment]
Seems to work great so far, I'll keep testing. Thanks for your quick response!
